version: "3"
services:
  dev:
    #image: blakeblackshear/frigate:stable-amd64
    restart: unless-stopped
    container_name: smarteyes-b1-faces
    user: root
    privileged: true
    shm_size: "256mb"

    #image: blakeblackshear/frigate:stable-amd64nvidia
    #image: blakeblackshear/frigate:stable
    #image: smarteyes:adm64nvidia
    #image: ghcr.io/blakeblackshear/frigate:dev-1ef109e-tensorrt
    #image: smarteyes:0.12.0-tensorrt
    image: diepho/smarteyes:latest-tensorrt 
    #image: diepho/smarteyes:latest-tensorrt
    #runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
#              count: 3
              device_ids: ['3']
              capabilities: [gpu]

    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility,video

    devices:
      - /dev/bus/usb:/dev/bus/usb
      - /dev/dri:/dev/dri
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./smarteyes-b1-faces.yml:/config/config.yml:rw
      - ../trt-models:/trt-models
      - /srv/vms/media/smarteyes-faces-12.0:/media/frigate
      - /srv/vms/tmp-faces:/tmp
    ports:
      - "5011:5000"
      - "1940:1935"
      - "1985:1984"
      - "8558:8554"
      - "8559:8555"
